// <auto-generated />
using System;
using Fiorello_Db.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Fiorello_Db.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240509105843_CreateBlogTable")]
    partial class CreateBlogTable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.29")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Fiorello_Db.Models.Blog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("SoftDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Blogs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Date = new DateTime(2024, 5, 9, 3, 58, 42, 739, DateTimeKind.Local).AddTicks(2267),
                            Description = "Description1",
                            Image = "blog-feature-img-1.jpg",
                            SoftDeleted = false,
                            Title = "Blog Title1"
                        },
                        new
                        {
                            Id = 2,
                            Date = new DateTime(2024, 5, 9, 3, 58, 42, 739, DateTimeKind.Local).AddTicks(2326),
                            Description = "Description2",
                            Image = "blog-feature-img-3.jpg",
                            SoftDeleted = false,
                            Title = "Blog Title2"
                        },
                        new
                        {
                            Id = 3,
                            Date = new DateTime(2024, 5, 9, 3, 58, 42, 739, DateTimeKind.Local).AddTicks(2331),
                            Description = "Description3",
                            Image = "blog-feature-img-4.jpg",
                            SoftDeleted = false,
                            Title = "Blog Title3"
                        });
                });

            modelBuilder.Entity("Fiorello_Db.Models.Slider", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("SoftDeleted")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Sliders");
                });
#pragma warning restore 612, 618
        }
    }
}
